<a href="https://colab.research.google.com/github/aishukambar/Digit-Recognition-Project/blob/master/Mnist_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import tensorflow as tf

In [17]:
mdata = tf.keras.datasets.mnist
(trainx,trainy),(testx,testy) = mdata.load_data()

In [18]:
#Defining a model
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(512,activation ='relu'))
model.add(tf.keras.layers.Dense(10,activation='softmax'))

In [19]:
model.compile(optimizer = 'adam',loss = 'sparse_categorical_crossentropy',metrics = 'accuracy')

In [20]:
history = model.fit(trainx,trainy,epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 5s 3ms/step - loss: 2.7124 - accuracy: 0.9049
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3503 - accuracy: 0.9360
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3155 - accuracy: 0.9405
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2741 - accuracy: 0.9456
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2531 - accuracy: 0.9498


In [21]:
y_pred = model.predict_classes(testx)
y_pred

array([7, 2, 1, ..., 4, 5, 6])

In [22]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [23]:
accuracy_score(y_pred,testy)

0.9206

In [24]:
confusion_matrix(y_pred,testy)

array([[ 940,    0,    2,    0,    0,    0,    3,    0,    1,    2],
       [   0, 1100,    0,    0,    4,    0,    2,    3,    0,    2],
       [   2,    4,  928,    2,    7,    0,    4,   23,    7,    1],
       [   2,    8,   62,  979,    1,   71,    0,   50,   75,   34],
       [   4,    0,    2,    0,  869,    1,    6,    6,    4,    6],
       [   1,    4,    1,    3,    3,  779,   10,    0,    5,    2],
       [   6,    6,    3,    1,   26,   12,  921,    2,   12,    5],
       [   6,    1,    7,    8,   17,    0,    1,  926,    0,   45],
       [  19,   11,   27,   17,   13,   23,   11,   10,  866,   14],
       [   0,    1,    0,    0,   42,    6,    0,    8,    4,  898]])

In [25]:
import numpy as np
np.argmax(model.predict(testx), axis=-1)

array([7, 2, 1, ..., 4, 5, 6])

In [26]:
model.get_weights()

[array([[ 0.04720616, -0.03480027, -0.02348145, ...,  0.01983417,
         -0.0395564 , -0.04456068],
        [-0.05258206, -0.05921216,  0.02958994, ..., -0.03813414,
         -0.04439026, -0.05144748],
        [ 0.04038867, -0.05137912, -0.01868688, ..., -0.04638626,
         -0.05221381, -0.0201195 ],
        ...,
        [ 0.0131565 ,  0.02371692,  0.00432818, ..., -0.05017791,
         -0.02278579, -0.00773416],
        [-0.01607601,  0.03678801, -0.06354854, ...,  0.04709177,
          0.01545624,  0.00415548],
        [-0.06534994, -0.04564537, -0.04947519, ...,  0.00785177,
          0.0426269 , -0.04272902]], dtype=float32),
 array([-0.03341728, -0.02769354, -0.05092475, -0.04206564, -0.03817781,
        -0.03467416, -0.04824594, -0.03357838, -0.0392493 , -0.01576404,
        -0.04560028, -0.01958955, -0.08222695, -0.02516995, -0.02186586,
        -0.01662732, -0.05383824, -0.04811984, -0.03216108, -0.02028936,
        -0.10623046, -0.03152575, -0.04674806, -0.0518885 ,  0.008

In [28]:
model.save("digit_Recognition.h5")